### ISSUE TITLE
More visible links

### ISSUE THREAD

**Issue by AngelOnFira** [CarletonComputerScienceSociety/carletoncomputersciencesociety.github.io#25]
In some pages, such as the /about/government/, we have links found at the end of the sentences. For ease of use, it may be better to feature them in the title, or under the description.

**Comment by l3rittny** [comment]
Good Idea! Also, we'll update the links to link to the team pages and have the board of directors link to the current board page in about the team.

**Comment by EricBellamy** [comment]
Changed link color to a more vibrant red
