### ISSUE TITLE
Remove link to SCS free software

### ISSUE THREAD

**Issue by wilsoliama** [CarletonComputerScienceSociety/carletoncomputersciencesociety.github.io#46]
Resources tab -> Useful Links -> Free Software

Link goes to page that no longer exists on the scs site

**Comment by EricBellamy** [comment]
Hey! I think this is fixed,

<img width="291" alt="screen shot 2018-09-06 at 12 27 32 pm" src="https://user-images.githubusercontent.com/7343076/45171408-47c1d780-b1d0-11e8-99f7-448ce235bfe2.png">

That is the link that I checked, and it now points [here](https://carleton.ca/scs/technical-support/scs-faculty-tech-resources/).
